---

- name: install flannel
  become: true
  yum: name=flannel state=present
#
- name: change flannel etcd key
  become: true
  lineinfile: dest=/etc/sysconfig/flanneld regexp='^FLANNEL_OPTIONS' line='FLANNEL_OPTIONS="-iface {{ flannel_host_nic }}"'
#
- name: set etcd key for flannel
  when: inventory_hostname == "{{ play_hosts[0] }}"
  command: etcdctl set /atomic.io/network/config {{ flannel_etcd_config }}
#
- name: configure firewall for flannel
  become: true
  command: firewall-cmd {{ item }}
  with_items:
    - --zone=public --add-port={{ flannel_backend_port }}/udp --permanent
    - --reload
#
- name: enable and start flanneld
  become: true
  command: systemctl {{ item }}
  with_items:
    - daemon-reload
    - enable flanneld
    - restart flanneld
#
- name: restart docker
  become: true
  command: systemctl restart docker
# ansible can not wait for udp port, instead use docker port
- name: wait for docker service up
  local_action: wait_for host={{ ansible_host }} port={{ docker_remote_port|regex_replace('\/tcp','') }} state=started delay=5 timeout=300
  any_errors_fatal: true
