FROM prireg:5000/alpine-s6-jdk8:3.4-8u112

MAINTAINER Hun Jae Lee <hunjae.lee@gmail.com>

ENV SPARK_VERSION=1.6.2 \
    HADOOP_PREBUILT_VERSION=2.6 \
    SPARK_HOME=/opt/spark 

RUN apk --update --no-cache add procps python mysql mysql-client \
    && wget -qO- http://apache.mirror.cdnetworks.com/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop$HADOOP_PREBUILT_VERSION.tgz | tar zxvf - -C /opt \
    && ln -s /opt/spark-$SPARK_VERSION-bin-hadoop$HADOOP_PREBUILT_VERSION $SPARK_HOME \
    && chown -R root:root /opt/spark-$SPARK_VERSION-bin-hadoop$HADOOP_PREBUILT_VERSION \
    && mkdir /data \
    && cp $SPARK_HOME/conf/spark-env.sh.template $SPARK_HOME/conf/spark-env.sh

WORKDIR $SPARK_HOME

VOLUME /data
