---

- hosts: cents
  any_errors_fatal: true
  vars:
    group_prefix: prod
    use_log_driver: false
#    public_interface: ansible_enp0s17
  vars_files:
    - vars/zookeeper.yaml
    - vars/kafka.yaml
    - vars/spark.yaml
    - vars/ignite.yaml
  tasks:
    - import_tasks: tasks/enable-kafka.yaml
      tags: ['kafka']

    - import_tasks: tasks/enable-zookeeper.yaml
      tags: ['zookeeper']

# depends on zookeeper
#    - import_tasks: tasks/enable-hadoop.yaml
#      tags: ['hadoop']

#    - import_tasks: tasks/enable-spark.yaml
#      tags: ['spark']

#    - import_tasks: tasks/enable-ignite.yaml
#      tags: ['ignite']
