FROM prireg:5000/hadoop-base:2.7.4
MAINTAINER Hun Jae Lee <hunjae.lee@gmail.com>

COPY core-site.xml.history-server $HADOOP_CONF_DIR/core-site.xml
COPY mapred-site.xml.history-server $HADOOP_CONF_DIR/mapred-site.xml
COPY yarn-site.xml.history-server $HADOOP_CONF_DIR/yarn-site.xml

RUN chown hduser:hdgroup $HADOOP_CONF_DIR/core-site.xml
RUN chown hduser:hdgroup $HADOOP_CONF_DIR/mapred-site.xml
RUN chown hduser:hdgroup $HADOOP_CONF_DIR/yarn-site.xml

COPY run-job-history-server /etc/services.d/job-history-server/run


## Job History Server Ports
EXPOSE 10020 10033 19888
