FROM alpine:3.4
MAINTAINER Hun Jae Lee <hunjae.lee@gmail.com>

RUN apk add --update --no-cache openssl alpine-sdk \
    && wget -qO- https://github.com/just-containers/s6-overlay/releases/download/v1.18.1.5/s6-overlay-amd64.tar.gz | tar zxvf - \
# compile and install su-exec
    && wget -qO- https://github.com/ncopa/su-exec/archive/v0.2.tar.gz | tar zxvf - \
    && cd su-exec* \
    && make \
    && mv su-exec /usr/bin \
    && cd .. \
    && rm -rf su-exec* \
    && apk del --no-cache openssl alpine-sdk

ENTRYPOINT ["/init"]
