---
# stop zookeeper servers
- name: shutdown and remove zookeeper cluster members
  shell: "/opt/zookeeper/bin/zkServer.sh stop"

- name: wait for zookeeper down
  local_action: wait_for host={{ ansible_host }} port={{ zookeeper_publish_2181 }} state=absent delay=5 timeout=3000

#- name: remove zookeeper product directory
#  become: true
#  file:
#    path: '{{ item }}'
#    state: absent
#  with_items:
#    - '/opt/zookeeper'
#    - '/opt/zookeeper-{{ zookeeper_version }}'

- name: change owner of data directory to root
  become: true
  shell: "chown -R root:root /{{ kafka_mount_root }}/{{ group_prefix }}/zookeeper"

- name: start zookeeper docker
  shell: "docker start {{ group_prefix }}-zookeeper"
