---
# stop kafka servers
- name: stop and remove Kafka cluster members
  shell: "/opt/kafka/bin/kafka-server-stop.sh"
  ignore_errors: yes

- name: wait for kafka down
  local_action: wait_for host={{ ansible_host }} port={{ kafka_publish_9092 }} state=absent delay=5 timeout=3000

#- name: remove kafka product directory
#  become: true
#  file:
#    path: '{{ item }}'
#    state: absent
#  with_items:
#    - '/opt/kafka'
#    - '/opt/kafka_{{ scala_binary_version }}-{{ kafka_version }}'

- name: start kafka docker
  shell: "docker start {{ group_prefix }}-kafka"
