---
- name: remove symbolic link
  become: true
  file:
    path: /opt/kibana
    state: absent

- name: remove installed directory, /opt/kibana-{{ kibana_version }}-linux-x86_64
  become: true
  file:
    path: /opt/kibana-{{ kibana_version }}-linux-x86_64
    state: absent
    
- name: remove data,log directories
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /data/kibana
    - /data/logs/elk
