#!/usr/bin/with-contenv sh

if [ -z ${SPARK_MASTER_IP+x} ]; then
  echo environment variable SPARK_MASTER_IP is unset. exiting...
  exit 1
fi
if [ -z ${SPARK_MASTER_PORT+x} ]; then
  echo environment variable SPARK_MASTER_PORT is unset. exiting...
  exit 1
fi

SPARK_WORKER_PORT=${SPARK_WORKER_PORT:-"40201"}
SPARK_WORKER_WEBUI_PORT=${SPARK_WORKER_WEBUI_PORT:-"8081"}
SPARK_WORKER_OPTS=${SPARK_WORKER_OPTS:-""}
SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY:-"1g"}
SPARK_WORKER_DIR=${SPARK_WORKER_DIR:-"/data/slave/work"}
SPARK_LOG_DIR=${SPARK_LOG_DIR:-"/data/slave/logs"}

ENV_SCRIPT=$SPARK_HOME/conf/spark-env.sh
echo SPARK_WORKER_PORT=$SPARK_WORKER_PORT >> $ENV_SCRIPT
echo SPARK_WORKER_WEBUI_PORT=$SPARK_WORKER_WEBUI_PORT >> $ENV_SCRIPT
echo SPARK_WORKER_OPTS=$SPARK_WORKER_OPTS >> $ENV_SCRIPT
echo SPARK_WORKER_MEMORY=$SPARK_WORKER_MEMORY >> $ENV_SCRIPT
echo SPARK_WORKER_DIR=$SPARK_WORKER_DIR >> $ENV_SCRIPT
echo SPARK_LOG_DIR=$SPARK_LOG_DIR >> $ENV_SCRIPT

echo "starting spark worker..." 
#exec /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port $SPARK_WORKER_WEBUI_PORT --port $SPARK_WORKER_PORT spark://$SPARK_MASTER_IP:$SPARK_MASTER_PORT
exec /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://$SPARK_MASTER_IP:$SPARK_MASTER_PORT
#exec /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
