---
# stop kafka servers
- name: stop and remove Kafka cluster members
  shell: "/opt/kafka/bin/kafka-server-stop.sh"
  ignore_errors: yes

#- name: remove kafka data directory - {{ kafka_mount_root }}/{{ group_prefix }}/kafka
#  become: true
#  file: 
#    path: '{{ kafka_mount_root }}/{{ group_prefix }}/kafka'
#    state: absent

- name: remove kafka product directory
  become: true
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/opt/kafka'
    - '/opt/kafka_{{ scala_binary_version }}-{{ kafka_version }}'
