---

- name: destroy elk services 
  when: inventory_hostname == "{{ play_hosts[0] }}"
  shell: docker service rm "{{ group_prefix}}-{{ item }}"
  with_items:
    -  kibana
    -  logstash
    -  elasticsearch
- name: Destroy its overlay network ({{ group_prefix}}-{{ elk_overlay_name }})
  when: inventory_hostname == "{{ play_hosts[0] }}"
  shell: docker network rm "{{ group_prefix }}-{{ elk_overlay_name }}"

- name: Remove ELK mount directory 
  when: inventory_hostname == "{{ play_hosts[0] }}"
  become: true
  file: path={{ elk_mount_root }}/elk state=absent
