#!/bin/bash
set -e

CASSANDRA_LISTEN_ADDRESS_COMMAND=${CASSANDRA_LISTEN_ADDRESS_COMMAND:-"hostname -i | awk '{print \$1}'"}
CASSANDRA_BROADCAST_ADDRESS_COMMAND=${CASSANDRA_BROADCAST_ADDRESS_COMMAND:-"${CASSANDRA_LISTEN_ADDRESS_COMMAND}"}
CASSANDRA_SEEDS_COMMAND=${CASSANDRA_SEEDS_COMMAND:-"${CASSANDRA_BROADCAST_ADDRESS_COMMAND}"}

export CASSANDRA_LISTEN_ADDRESS=${CASSANDRA_LISTEN_ADDRESS:-$(eval $CASSANDRA_LISTEN_ADDRESS_COMMAND)}
export CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS:-$(eval ${CASSANDRA_BROADCAST_ADDRESS_COMMAND})}
export CASSANDRA_SEEDS=${CASSANDRA_SEEDS:-$(eval ${CASSANDRA_SEEDS_COMMAND})}

echo CASSANDRA_LISTEN_ADDRESS=$CASSANDRA_LISTEN_ADDRESS
echo CASSANDRA_BROADCAST_ADDRESS=$CASSANDRA_BROADCAST_ADDRESS
echo CASSANDRA_SEEDS=$CASSANDRA_SEEDS

/docker-entrypoint.sh "$@"
